# XLLL PERSONAL CONFIG FOR CAELESTIA
# Permanent user config, loaded last by Caelestia.

# === Monitor: MSI MAG345CQR 3440x1440 180Hz scale 1.25 ===
monitor = DP-2, 3440x1440@180.00, 0x0, 1.25
monitor = DP-1, 3440x1440@180.00, 0x0, 1.25
monitor = HDMI-A-1, 3440x1440@180.00, 0x0, 1.25
monitor = , preferred, auto, 1

# === Keyboard + mouse ===
input {
    kb_layout = us,ru,ua
    kb_variant = ,,
    kb_options = grp:alt_shift_toggle
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
}

# Logitech M705 / normal mouse no acceleration
device {
    name = logitech-m705
    sensitivity = 0
    accel_profile = flat
}

general {
    allow_tearing = false
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
